// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded to user's own Supabase project (overrides any .env values that
// Lovable Cloud may regenerate). Do not revert to import.meta.env.
const SUPABASE_URL = 'https://zahhxugltdrzivnocqoq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_jdXqXeSs_nGvaY7hxa8THA_waOef8eD';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
